openapi: '3.0.3'

info:
  title: 'Order Application API Spec'
  version: 0.0.1

servers:
  - url: http://localhost:10001
    description: Development server

paths:
  /api/orders:
    post:
      description: 주문한다.
      operationId: createOrder
      tags:
        - Order
      requestBody:
        description: createOrder model
        content:
          application/vnd.vroong.private.v1+json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Ok
          content:
            application/vnd.vroong.private.v1+json:
              schema:
                $ref: '#/components/schemas/Order'
#                배송비, 총 결제 금액, 주문 상품 목록
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

    get:
      description: 주문 목록을 조회한다.
      operationId: getOrderList
      tags:
        - Order
      responses:
        '200':
          description: Ok
          content:
            application/vnd.vroong.private.v1+json:
              schema:
                $ref: '#/components/schemas/OrderList'
        #                배송비, 총 결제 금액, 주문 상품 목록
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/orders/{orderId}:
    parameters:
      - $ref: '#/components/parameters/OrderIdParam'

    get:
      description: 개별 주문을 조회한다.
      operationId: getOrder
      tags:
        - Order
      responses:
        '200':
          description: Ok
          content:
            application/vnd.vroong.private.v1+json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    patch:
      description: 주문을 수정한다.
      operationId: updateOrder
      tags:
        - Order
      requestBody:
        description: updateOrder model
        content:
          application/vnd.vroong.private.v1+json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      description: 주문을 취소한다.
      operationId: cancelOrder
      tags:
        - Order
      responses:
        '200':
          description: Ok
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/exceptions:
    get:
      description: Test Exceptions
      operationId: getException
      tags:
        - Example
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum:
              - ServerError
              - NoSuchElement
      responses:
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:

    #----------------------------------------
    # API fields
    #----------------------------------------

    IntId:
      type: integer
      format: int32
      example: 1

    LongId:
      type: integer
      format: int64
      example: 1

    DateTime:
      type: string
      format: date-time
      example: "2018-12-01T10:00:00Z"

    StringField:
      type: string
      example: "foo"

    UUID:
      type: string
      format: uuid
      example: c9106593-2d6c-40eb-8504-66b0ef41ad2d

    #----------------------------------------
    # Common Model
    #----------------------------------------

    LongArray:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/LongId'

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
          example: template/constraint-violation
        title:
          type: string
          example: 제출한 요청이 유효하지 않습니다
        detail:
          type: string
        fieldErrors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/FieldError'

    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          $ref: '#/components/schemas/ErrorCode'

    ErrorCode:
      type: string
      example:
        - NotNull
        - Size

    Page:
      type: object
      properties:
        size:
          type: integer
          format: int32
          default: 20
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 100
        totalPages:
          type: integer
          format: int32
          example: 5
        number:
          type: integer
          format: int32
          default: 1
          example: 1

    #----------------------------------------
    # API Model
    #----------------------------------------

    UserInfo:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/StringField'
        phoneNumber:
          $ref: '#/components/schemas/StringField'
        address:
          $ref: '#/components/schemas/StringField'

    OrderLine:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OrderLineItem'

    OrderLineItem:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/OrderProduct'
        quantity:
          type: integer
          format: int32
          example: 10

    OrderProduct:
      type: object
      properties:
        productId:
          $ref: '#/components/schemas/LongId'
        name:
          $ref: '#/components/schemas/StringField'
        price:
          type: number
          example: 10000

    OrderState:
      type: string
      enum: [PLACED, PAYMENT_APPROVED, DELIVERY_STARTED, DELIVERY_COMPLETED, CANCELED]

    Order:
      type: object
      properties:
        orderId:
          $ref: '#/components/schemas/LongId'
        orderer:
          $ref: '#/components/schemas/UserInfo'
        receiver:
          $ref: '#/components/schemas/UserInfo'
        orderState:
          $ref: '#/components/schemas/OrderState'
        orderLine:
          $ref: '#/components/schemas/OrderLine'
        deliveryFee:
          type: number
          example: 3000
        totalPrice:
          type: number
          example: 10000

    OrderList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        page:
          $ref: '#/components/schemas/Page'

  parameters:

    PageParam:
      in: query
      name: page
      schema:
        type: integer
        format: int32
        default: 1

    SizeParam:
      in: query
      name: size
      schema:
        type: integer
        format: int32
        default: 10

    OrderIdParam:
      in: path
      name: orderId
      description: Order ID
      schema:
        type: integer
        format: int64
      example: 12345
      required: true

  responses:

    Created:
      description: Created

    Accepted:
      description: Accepted

    NoContent:
      description: No Content

    EmptyContent:
      description: No Content
      content:
        application/vnd.vroong.private.v1+json: { }

    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    ServerError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

  securitySchemes:
    'jhipster-uaa':
      type: oauth2
      flows:
        password:
          tokenUrl: http://localhost:9999/uaa/oauth/token
          refreshUrl: http://localhost:9999/uaa/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: http://localhost:9999/uaa/oauth/token
          scopes: {}

security:
  - jhipster-uaa: []
